# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Program_Station/Embedded_Program/GOWIN_FPGA/dds_fpga_control/sim/uart_spi_demo/uart_spi_demo.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Program_Station/Embedded_Program/GOWIN_FPGA/dds_fpga_control/sim/uart_spi_demo/uart_spi_demo.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Program_Station/Embedded_Program/GOWIN_FPGA/dds_fpga_control/sim/uart_spi_demo/uart_spi_demo.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Program_Station/Embedded_Program/GOWIN_FPGA/dds_fpga_control/sim/uart_spi_demo/uart_spi_demo.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Program_Station/Embedded_Program/GOWIN_FPGA/dds_fpga_control/sim/uart_spi_demo/uart_spi_demo.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Program_Station/Embedded_Program/GOWIN_FPGA/dds_fpga_control/sim/uart_spi_demo/uart_spi_demo.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Program_Station/Embedded_Program/GOWIN_FPGA/dds_fpga_control/sim/uart_spi_demo/uart_spi_demo.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Program_Station/Embedded_Program/GOWIN_FPGA/dds_fpga_control/sim/uart_spi_demo/uart_spi_demo.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
